Categories
IgnacioCava/rb-bc-ecom pull request #11
Opened 2022-04-04 16:43 UTC by IgnacioCava

2022-04-05 14:16 UTC, bsfmtl123 requested changes

2022-04-05 14:16 UTC, omerzn commented on src/components/ProductsHolder/ProductsHolder.jsx
> +    const optionsRef = useMemo(() => [createRef(), createRef()], [])
why are you using a useMemo here?

2022-04-05 14:16 UTC, omerzn commented on src/components/ProductsHolder/ProductsHolder.jsx
> +    },[scrollType, optionsRef])
refs persist between renders.

2022-04-05 15:12 UTC, IgnacioCava commented on src/components/ProductsHolder/ProductsHolder.jsx
> +    const optionsRef = useMemo(() => [createRef(), createRef()], [])
React is recommending me to use useMemo there to account for the deps of the useEffect below it. It works anyways, but it's the only way of making the missing dependency error message go away

2022-04-06 10:29 UTC, bsfmtl123 approved these changes

2022-04-06 10:29 UTC, merged